### ISSUE TITLE
JBEAM DONT EXPORT !!!

### ISSUE THREAD

**Issue by FADONES** [BeamNG/Blender-JBeam-Editor#22]
Why when I change the Jbeam in blender and export it it does not change in the files and in the game???

**Comment by angelo234** [comment]
Did you run Blender as an administrator? Any error messages in the "System Console" (https://blender.stackexchange.com/a/145891)?

**Comment by FADONES** [comment]
Я запускаю с правами администратора, в консоле есть ошибка.

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 1053, in poll_active_operators
    refresh_curr_vdata(True)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 622, in refresh_curr_vdata
    curr_vdata = pickle.loads(obj_data[constants.MESH_SINGLE_JBEAM_PART_DATA])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: pickle data was truncated

**Comment by FADONES** [comment]
I run it with administrator rights, this may be an error in the console.

_pickle.UnpicklingError: pickle data was truncated
Error in bpy.app.handlers.depsgraph_update_post[0]:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 1011, in depsgraph_callback
    refresh_curr_vdata()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 622, in refresh_curr_vdata
    curr_vdata = pickle.loads(obj_data[constants.MESH_SINGLE_JBEAM_PART_DATA])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: pickle data was truncated
Error in bpy.app.handlers.depsgraph_update_post[0]:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 1011, in depsgraph_callback
    refresh_curr_vdata()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 622, in refresh_curr_vdata
    curr_vdata = pickle.loads(obj_data[constants.MESH_SINGLE_JBEAM_PART_DATA])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: pickle data was truncated
Error in bpy.app.handlers.depsgraph_update_post[0]:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 1011, in depsgraph_callback
    refresh_curr_vdata()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 622, in refresh_curr_vdata
    curr_vdata = pickle.loads(obj_data[constants.MESH_SINGLE_JBEAM_PART_DATA])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: pickle data was truncated
Error in bpy.app.handlers.depsgraph_update_post[0]:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 1011, in depsgraph_callback
    refresh_curr_vdata()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor\__init__.py", line 622, in refresh_curr_vdata
    curr_vdata = pickle.loads(obj_data[constants.MESH_SINGLE_JBEAM_PART_DATA])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: pickle data was truncated
Exported to disk: vector_taillight_R, vector_taillight_L, vector_taillight_L_white, vector_taillight_R_white
Exporting Time 0.14 s

**Comment by angelo234** [comment]
What version are you on?

**Comment by FADONES** [comment]
latest version of the plugin, reinstalled today

**Comment by FADONES** [comment]
there is also a bug in that it is still exported, but not in the place where I did it in blender

**Comment by FADONES** [comment]
No, either nothing changes for me after export, or there is a bug described by me above, I don’t know how to fix it, please help

**Comment by angelo234** [comment]
Try removing the installed plugin and reinstall

**Comment by FADONES** [comment]
I tried to reinstall the plugin and now I can't install the plugin with this error

Traceback (most recent call last):
  File "C:\Games\Steam\steamapps\common\Blender\4.2\scripts\startup\bl_operators\userpref.py", line 732, in execute
    file_to_extract.extractall(path_addons)
  File "C:\Games\Steam\steamapps\common\Blender\4.2\python\Lib\zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Games\Steam\steamapps\common\Blender\4.2\python\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\scripts\\addons\\Blender-JBeam-Editor-main\\tests\\vehicle_import_modify_export\\delete_beams\\test_1\\expected\\vehicles\\agenty_legocar\\jbeam\\lights\\headlights\\facelift_housing\\legocar_headlight_L_facelift.jbeam'

**Comment by angelo234** [comment]
Hmm thats a pretty bizarre error and seems to be related specifically to Blender

**Comment by angelo234** [comment]
Can you try to delete the addon from C:\Users\your_username\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\jbeam_editor

**Comment by angelo234** [comment]
And try installing the plugin again

**Comment by angelo234** [comment]
Wait did you download the "blender_jbeam_editor_0.2.5.zip" file from https://github.com/BeamNG/Blender-JBeam-Editor/releases/tag/v0.2.5

**Comment by FADONES** [comment]
No, I'll download it now

**Comment by angelo234** [comment]
It looks like you might have downloaded the zip file containing the entire Github repository which is not correct

**Comment by FADONES** [comment]
Everything worked and now the jbeam changes when exporting

**Comment by FADONES** [comment]
thank you !
